version: '2'

services:
  postgres:
    image: postgres:9.6
    build: ./database/
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - POSTGRES_PASSWORD=postgres
      - INIT_DB_ONLY=False
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate --settings=$SETTINGS_TO_RUN &&
               ./manage.py runserver --settings=$SETTINGS_TO_RUN 0.0.0.0:8080"
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres